sourceDirectory: /usr/local/var/temp_files
validRdfFormats:
  - { format: "turtle", mimeType: "text/turtle", extension : "ttl" }
  - { format: "jsonld", mimeType: "application/ld+json", extension: "jsonld" }
  - { format: "ntriples", mimeType: "application/n-triples", extension: "n3" }
defaultRdfFormat: turtle
